### PR TITLE
Add database support

### LINKED ISSUE #43: Add mysql Support
Would be very useful, thanks for a great project.

### PR DESCRIPTION
**Pull request by celsworth**
Adds support for storing input data to a database.

Postgres, MySQL, and SQLite are all supported.

Closes #43

### CODE REVIEW

**Comment by zatie12** [comment]
Running with mysql and working well. Thanks again for the fast turnaround!

**Comment by celsworth** [comment]
Thanks for testing! I'll give this another day or two for any bug reports you may find or any other improvements I think of then merge it.

**Comment by zatie12** [comment]
The import working without any issues (410 rows added so far) however I noticed if the mysql server is restarted, lxp-bridge exits on the next update:

```
Mar 21 09:34:38 miranda lxp-bridge[462137]: [2022-03-21T09:34:38.250 ERROR lxp_bridge] error communicating with database: connection aborted
Mar 21 09:34:38 miranda lxp-bridge[462137]: Caused by:
Mar 21 09:34:38 miranda lxp-bridge[462137]:     connection aborted
Mar 21 09:34:38 miranda systemd[1]: lxp-bridge.service: Main process exited, code=exited, status=255/EXCEPTION
Mar 21 09:34:38 miranda systemd[1]: lxp-bridge.service: Failed with result 'exit-code'.
Mar 21 09:34:38 miranda systemd[1]: lxp-bridge.service: Consumed 1.147s CPU time.
Mar 21 09:34:43 miranda systemd[1]: lxp-bridge.service: Scheduled restart job, restart counter is at 1.
Mar 21 09:34:43 miranda systemd[1]: Stopped lxp-bridge.
Mar 21 09:34:43 miranda systemd[1]: lxp-bridge.service: Consumed 1.147s CPU time.
Mar 21 09:34:43 miranda systemd[1]: Started lxp-bridge.
Mar 21 09:34:43 miranda lxp-bridge[2438123]: [2022-03-21T09:34:43.314 INFO lxp_bridge] lxp-bridge 0.7.0-dev starting
```

Thanks

**Comment by celsworth** [comment]
Ah thanks, I must need to add a bit more checking around reconnections. I'll take a look today :)

**Pull request merged**
