### PR TITLE
Add meaningful names to Home Assistant

### PR DESCRIPTION
**Pull request by chriscn**
I find that these names are more useful than the specific configuration strings, they aren't all perfect and might need some further tweaking but for now I feel that it is a good start.

It would be nice as a configuration option as to whether or not expose the individual strings, personally I just have one string and benefit from just having the `e_pv_all` etc.

But thank you for all the work you've done on this project. There are some teething issues getting it installed (and I think that mine crashed but am trying to figure out why).

### CODE REVIEW

**Comment by celsworth** [comment]
Hm also do the autodiscovery packets need updating?

**Comment by celsworth** [comment]
Ah now I remember, sorry. Been a while since I touched this :)

https://github.com/celsworth/lxp-bridge/blob/master/src/home_assistant.rs#L61 relies on the name matching the JSON keys in the MQTT data packets. Basically it tells HA that, for example, `p_pv` can be found by looking in the `p_pv` key of `inputs/1`. 

By changing the name here that won't work anymore. You should be able to test this by resetting your HA config (insofar as the inverter config goes) and then letting it re-detect the sensors using your new names - I think it won't populate the values anymore.

So I think we need to split up the name and label - the name can be used like it is now, then the label is used [here](https://github.com/celsworth/lxp-bridge/blob/master/src/home_assistant.rs#L67).

**Comment by chriscn** [comment]
Time to revert my commit then! I'm not brilliant with Rust but have got an idea so will commit some changes and see what you think. Likewise the project is very early and so I think that changing (and improving) isn't a bad thing.

My understanding of Home Assistant is that if you hadn't updated your names it would change them but if you set a custom name it keeps it the same.

**Comment by chriscn** [comment]
I've added a label field to the temperature function? I'm not great with Rust so let me know if you think it would work?

**Comment by celsworth** [comment]
Yep that looks about right :) I think we need to keep the datalog though, so people with multiple inverters can differentiate between them. This isn't as uncommon as you might think as they support parallel operation for lots more batteries.

Can you test this on your HA?

**Comment by chriscn** [comment]
Screenshot 2022-04-14 at 18 08 30
Personally I believe it looks better without the ID; the entity ID always contains the correct value if people need to check and rename?

**Comment by chriscn** [comment]
Screenshot 2022-04-14 at 18 19 15

**Comment by celsworth** [comment]
Nice, yeah I'm happy to merge this. It's a definite improvement. I don't have a strong opinion on keeping the inverter serial in the label I suppose, so lets remove it and revisit if anyone finds it a problem in future.

**Pull request merged**
