### PR TITLE
Add availability object to HA discovery messages

### PR DESCRIPTION
**Pull request by celsworth**
This should let HA know when lxp-bridge goes offline and will disable switches accordingly.

### CODE REVIEW

**Comment by celsworth** [comment]
@unreadablename I think you use HA a lot, could you verify if this has the appropriate effect?

When lxp-bridge exits now, HA should know about it and perhaps display that the sensors are offline? Then when you restart it, they should become online again. It might only really matter for switches (coming soon) but I added it for sensors too.

**Comment by unreadablename** [comment]
@celsworth I'm constantly seeing `offline` at `{namespace}/LWT` and that's why all sensors are `Unavailable`

**Comment by celsworth** [comment]
Oh no :(

If you restart lxp-bridge then it should publish `online` as a retained message. That should then persist until lxp-bridge quits. Is this not happening for you?

**Comment by unreadablename** [comment]
It becomes available for a moment, and then again offline

**Comment by unreadablename** [comment]
hmm
looks like it's an mqtt issue

```[2022-12-09T13:01:22.326 ERROR lxp_bridge::mqtt] Mqtt state: Io error: Custom { kind: ConnectionAborted, error: "connection closed by peer" }
[2022-12-09T13:01:22.326 INFO lxp_bridge::mqtt] reconnecting in 5s
[2022-12-09T13:01:32.332 ERROR lxp_bridge::mqtt] Mqtt state: Io error: Custom { kind: ConnectionAborted, error: "connection closed by peer" }
[2022-12-09T13:01:32.332 INFO lxp_bridge::mqtt] reconnecting in 5s
[2022-12-09T13:01:42.339 ERROR lxp_bridge::mqtt] Mqtt state: Io error: Custom { kind: ConnectionAborted, error: "connection closed by peer" }
[2022-12-09T13:01:42.339 INFO lxp_bridge::mqtt] reconnecting in 5s
[2022-12-09T13:01:52.345 ERROR lxp_bridge::mqtt] Mqtt state: Io error: Custom { kind: ConnectionAborted, error: "connection closed by peer" }
[2022-12-09T13:01:52.345 INFO lxp_bridge::mqtt] reconnecting in 5s
[2022-12-09T13:02:02.351 ERROR lxp_bridge::mqtt] Mqtt state: Io error: Custom { kind: ConnectionAborted, error: "connection closed by peer" }
[2022-12-09T13:02:02.351 INFO lxp_bridge::mqtt] reconnecting in 5s
[2022-12-09T13:02:12.358 ERROR lxp_bridge::mqtt] Mqtt state: Io error: Custom { kind: ConnectionAborted, error: "connection closed by peer" }
[2022-12-09T13:02:12.358 INFO lxp_bridge::mqtt] reconnecting in 5s
[2022-12-09T13:02:22.363 ERROR lxp_bridge::mqtt] Mqtt state: Io error: Custom { kind: ConnectionAborted, error: "connection closed by peer" }
[2022-12-09T13:02:22.363 INFO lxp_bridge::mqtt] reconnecting in 5s
```

**Comment by celsworth** [comment]
You definitely only have one lxp-bridge instance running?

Or is this perhaps an older broker that doesn't support LWT? But that would probably be unusual.

**Comment by unreadablename** [comment]
yeap, I don't know why, but HA restarted manually stopped instance of addon

**Comment by unreadablename** [comment]
it works correctly

**Comment by celsworth** [comment]
👍 thanks :)

**Pull request merged**
